/* SPDX-License-Identifier: GPL-2.0 */


#ifndef __QCOM_RPMH_REGULATOR_H
#define __QCOM_RPMH_REGULATOR_H


#define RPMH_REGULATOR_MODE_RET		0
#define RPMH_REGULATOR_MODE_LPM		1
#define RPMH_REGULATOR_MODE_AUTO	2
#define RPMH_REGULATOR_MODE_HPM		3

#endif
