/* SPDX-License-Identifier: GPL-2.0-or-later */


#define LOCAL_CONTROL			0x000
#define LOCAL_PRESCALER			0x008


#define LOCAL_GPU_ROUTING		0x00c

#define LOCAL_PM_ROUTING_SET		0x010

#define LOCAL_PM_ROUTING_CLR		0x014

#define LOCAL_TIMER_INT_CONTROL0	0x040

#define LOCAL_MAILBOX_INT_CONTROL0	0x050

#define LOCAL_IRQ_PENDING0		0x060

#define LOCAL_FIQ_PENDING0		0x070

#define LOCAL_MAILBOX0_SET0		0x080
#define LOCAL_MAILBOX3_SET0		0x08c

#define LOCAL_MAILBOX0_CLR0		0x0c0
#define LOCAL_MAILBOX3_CLR0		0x0cc

#define LOCAL_IRQ_CNTPSIRQ	0
#define LOCAL_IRQ_CNTPNSIRQ	1
#define LOCAL_IRQ_CNTHPIRQ	2
#define LOCAL_IRQ_CNTVIRQ	3
#define LOCAL_IRQ_MAILBOX0	4
#define LOCAL_IRQ_MAILBOX1	5
#define LOCAL_IRQ_MAILBOX2	6
#define LOCAL_IRQ_MAILBOX3	7
#define LOCAL_IRQ_GPU_FAST	8
#define LOCAL_IRQ_PMU_FAST	9
#define LAST_IRQ		LOCAL_IRQ_PMU_FAST
