

#ifndef DT_BINDINGS_CLOCK_AMLOGIC_MESON_GXBB_AOCLK
#define DT_BINDINGS_CLOCK_AMLOGIC_MESON_GXBB_AOCLK

#define CLKID_AO_REMOTE		0
#define CLKID_AO_I2C_MASTER	1
#define CLKID_AO_I2C_SLAVE	2
#define CLKID_AO_UART1		3
#define CLKID_AO_UART2		4
#define CLKID_AO_IR_BLASTER	5
#define CLKID_AO_CEC_32K	6
#define CLKID_AO_CTS_OSCIN	7
#define CLKID_AO_32K_PRE	8
#define CLKID_AO_32K_DIV	9
#define CLKID_AO_32K_SEL	10
#define CLKID_AO_32K		11
#define CLKID_AO_CTS_RTC_OSCIN	12
#define CLKID_AO_CLK81		13

#endif
